# Random

### NumPy Random
    NumPy memiliki fungsi khusus bernama random. Untuk mendapatkan angka-angka secara random(pseudo random).

In [4]:
from numpy import random
import numpy as np

### Mendapatkan nilai integer secara random

In [15]:
x = random.randint(100)
y = random.randint(100, size=1)
z = random.randint(100, size=(3, 2))

print(x)
print(y)
print(z)

# Sama seperti di Python dia akan mengeluarkan angka acak dari 0-99

37
[86]
[[79 31]
 [ 1 27]
 [52 85]]


### Mendapatkan nilai float secara random

In [ ]:
x = random.rand()     # Hasilnya dalam bentuk skalar float
y = random.rand(2)   # Hasilnya dalam bentuk array 1D
z = random.rand(2, 3) # Hasilnya dalam bentuk array 2D

print(x)
print(y)
print(z)

0.09265992834046066
[0.70550975 0.02516005]
[[0.79736717 0.63177362 0.97217603]
 [0.42910477 0.2214277  0.72784987]]


### Membuat nilai integer random dari Array 1D

In [19]:
x = random.choice([1, 2, 3, 4, 5])
y = random.choice([1, 2, 3, 4, 5], size=2)
z = random.choice([1, 2, 3, 4, 5], size=(2, 3))

print(x)
print(y)
print(z)

3
[1 1]
[[4 2 5]
 [5 4 1]]


### Mengacak nilai yang ada pada Array 1D

In [5]:
arr =  np.array([1, 2, 3, 4, 5])
random.shuffle(arr) # Mengacak urutan array

print(arr)

[3 5 1 4 2]
