# SHAPE

### Array Shape

In [4]:
#Mendapatkan shape dari array
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [3]:
#Menggunakan ndmin untuk mendefinisikan dimensiabs
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


### Array Reshape

In [7]:
#Reshape dari 1D ke 2D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr = arr.reshape(2, 5)
print(arr)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [35]:
#Reshape dari 1D ke 3D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr = arr.reshape(3, 2, 2)
print(arr)
print(arr.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [36]:
#Reshape dari 1D ke 3D menggunakan (-1)
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr = arr.reshape(2, 2, -1)
print(arr)
print(arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


### Array Flattening

In [37]:
#Menggunakan reshape(-1)
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = arr.reshape(-1)
print(arr)

[1 2 3 4 5 6]


In [38]:
#Menggunakan flatten()
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = arr.flatten()
print(arr)

[1 2 3 4 5 6]


### Array Copy & View

In [39]:
#Contoh copy()
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr, x)

#jadi kalau menggunakan copy() kita ubah elemen di parent maka di childnya tidak ikut berubah

[42  2  3  4  5] [1 2 3 4 5]


In [40]:
#Contoh view()
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr, x)

#Tapi kalau kita menggunakan view() jika kita ubah element di parent maka di child juga ikut berubah

[42  2  3  4  5] [42  2  3  4  5]
