# Praktek Shape

### Mendapatkan shape dari Array

In [1]:
import numpy as np

In [4]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

#bisa juga cek jumlah elemen dari keseluruhan
print(arr.size)

#bisa juga cek jumlah dimensi
print(arr.ndim)

(2, 4)
8
2


### Menggunakan (ndmin=) untuk mendefinisikan dimensi

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=3)
print(arr)

#Cek shape
print(arr.shape)

#Cek jumlah dimensi
print(arr.ndim)

[[[1 2 3 4]]]
(1, 1, 4)
3


### Reshape dari 1D ke 2D

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.shape

(12,)

In [23]:
arr = arr.reshape(4, 3)
arr.shape, arr, arr.ndim

((4, 3),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 2)

### Reshape dari 1D ke 3D

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.shape

(12,)

In [22]:
arr = arr.reshape(2, 3, 2)
arr.shape, arr, arr.ndim

((2, 3, 2),
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],
 
        [[ 7,  8],
         [ 9, 10],
         [11, 12]]]),
 3)

### Reshape -1 pada proses reshaping

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.shape

(12,)

In [26]:
arr = arr.reshape(4, 3, -1)
arr.shape, arr, arr.ndim

((4, 3, 1),
 array([[[ 1],
         [ 2],
         [ 3]],
 
        [[ 4],
         [ 5],
         [ 6]],
 
        [[ 7],
         [ 8],
         [ 9]],
 
        [[10],
         [11],
         [12]]]),
 3)

### Melakukan flattening pada Array (Meratakan jadi 1D)

In [27]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr.ndim

2

In [30]:
arr = arr.flatten()
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
arr.ndim

1

# Melakukan duplikasi array

### Menggunakan copy

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = arr.copy()
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
arr[0] = 42
arr, x

(array([42,  2,  3,  4,  5,  6,  7,  8]), array([1, 2, 3, 4, 5, 6, 7, 8]))

In [35]:
# jika menggunakan copy() maka x yang menjadi child dari arr tidak ikut berubah ketika kita mengubah parent

### Menggunakan view()

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = arr.view()
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
arr[0] = 42
arr, x

(array([42,  2,  3,  4,  5,  6,  7,  8]),
 array([42,  2,  3,  4,  5,  6,  7,  8]))

In [38]:
# nah jika kita menggunakan view() maka child juga ikut berubah ketika kita mengubah parent