<a href="https://colab.research.google.com/github/rubythalib33/Sekolah-AI-Indonesia/blob/main/Course%201.%20Pytorch%2BLightning%20Coureses%20Level%201/1_2_ANN_training_with_dummy_datasets_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.2 ANN training with dummy datasets

Syllabus:
1. create a linear function for the dummy datasets
2. create dummy datasets
3. create model
4. create training scheme
5. create inference function

## 1. create a linear function for the dummy datasets

for this tutorial we are gonna make this function for the datasets,
f(x1,x2,x3,x4) = x1*w1+x2*w2+x3*w3+x4*w4
w1 = 1
w2 = 2
w3 = 3
w4 = 4

In [1]:
def function(x1, x2, x3, x4):
  w1,w2,w3,w4 = 1,2,3,4
  return  x1*w1+x2*w2+x3*w3+x4*w4

In [2]:
#example
x1,x2,x3,x4 = 1,2,3,4
function(x1,x2,x3,x4) #1+4+9+16=30

30

## 2. create dummy datasets


In [3]:
import numpy as np

In [4]:
def create_dummy_datasets(n=1000):
  x = np.random.randint(0, 2000, size=(n,4))

  y = []
  for i in x:
    y_temp = function(*i) #i[0], i[1], ..., i[n-1] n: panjang arraynya
    y.append(y_temp)

  y = np.asarray(y)

  return x,y

In [5]:
N_SAMPLE = 1000
data = create_dummy_datasets(N_SAMPLE)

In [6]:
print(data[0]) #for the x data
print(data[1]) #for the y data

[[1177  141 1065  461]
 [ 789  716  737  664]
 [ 526  384  150  556]
 ...
 [1422 1300 1641 1326]
 [ 848 1022  239  352]
 [1692 1954 1923 1040]]
[ 6498  7088  3968 10109  7944  8230 11564  9551 11034 14800 12369 13486
 12324  8602  6202 11760 11386  8702 11504 13987  7033 15602 17382 12560
 12638  7568 11082  8823  5994 12708 14606 15546 15503  7436  9017 16325
 11674  8191 10099 15608 12177 13249 17167  6405 13764 11258 12413 11923
  9794 15152 10827  9067  6591 14687 13883  7473 10852 10654  9240 12652
  8266 14444 10129 14510  6776  9512 14883 16383 13014  8603  8965  5094
 13882  6943  3351 10101 14079 15898 10511  7342  8473  4045 15406  8863
 13835 14719 10030 10460  8352 16546  6400  8011 14628 10104  9548  2790
 13094 11872  7323 12228  8253  5872  7569  6280  7660  9800 12015  9611
 12021  8968 13279  8416  8095  6281  9523 12855 10863 14683 13892 10493
 11165 11883  5819  8234 11012  6286 13673 11533  9781  6058  6804  8424
 13725  8719  6218 15135 13924  9487  6068  7503  835

In [7]:
#lets convert it to torch.tensor dtype torch.float32 so it can run smoothly on neural nets
import torch

In [8]:
X = torch.tensor(data[0], dtype = torch.float32)
y = torch.tensor(data[1], dtype = torch.float32)

In [9]:
print(X)
print(y)

tensor([[1177.,  141., 1065.,  461.],
        [ 789.,  716.,  737.,  664.],
        [ 526.,  384.,  150.,  556.],
        ...,
        [1422., 1300., 1641., 1326.],
        [ 848., 1022.,  239.,  352.],
        [1692., 1954., 1923., 1040.]])
tensor([ 6498.,  7088.,  3968., 10109.,  7944.,  8230., 11564.,  9551., 11034.,
        14800., 12369., 13486., 12324.,  8602.,  6202., 11760., 11386.,  8702.,
        11504., 13987.,  7033., 15602., 17382., 12560., 12638.,  7568., 11082.,
         8823.,  5994., 12708., 14606., 15546., 15503.,  7436.,  9017., 16325.,
        11674.,  8191., 10099., 15608., 12177., 13249., 17167.,  6405., 13764.,
        11258., 12413., 11923.,  9794., 15152., 10827.,  9067.,  6591., 14687.,
        13883.,  7473., 10852., 10654.,  9240., 12652.,  8266., 14444., 10129.,
        14510.,  6776.,  9512., 14883., 16383., 13014.,  8603.,  8965.,  5094.,
        13882.,  6943.,  3351., 10101., 14079., 15898., 10511.,  7342.,  8473.,
         4045., 15406.,  8863., 13835.

## 3.lets build a model

In [10]:
from torch import nn

# nn = neuaral network

In [11]:
class RegressionModel(nn.Module):
  def __init__(self, input_node=4, output_node=1):   # input_node=4 diambil dari jumlah input variabel = 4
    super().__init__()
    self.input_node = input_node
    self.output_node = output_node

    self.fc = nn.Linear(self.input_node, self.output_node, bias=False) #we want to make the bias false so it can relate with the function but in most cases you need the bias to be true

  def forward(self,x):
    return self.fc(x)

## 4. Let's Create training scheme
before that let's understand about concept of optimization and loss function

In [12]:
sample_model = RegressionModel()
optim = torch.optim.SGD(sample_model.parameters(), lr=0.001) #Stochastic Gradient Descent
loss_fn = nn.MSELoss() #Mean Squared error loss

In [13]:
sample_X = X
sample_y = y

BATCH_SIZE = 10
sample_X = torch.reshape(sample_X, (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 4)) #let's make batch 10 | (N_SAMPLE,4) -> (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 4) -> (100, 10, 4)
sample_y = torch.reshape(sample_y, (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 1)) #let's make batch 10 | (N_SAMPLE,1) -> (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 1) -> (100, 10, 1)


# scale data
# normalisasi sederhana dibagi dengan 2000 agar nilainya menjadi 0-1 karena dibagi angka maksimalnya dari N_SAMPLE
sample_X = sample_X/2000
sample_y = sample_y/2000

In [14]:
print(sample_X.shape)
print(sample_y.shape)
print(sample_model)

torch.Size([100, 10, 4])
torch.Size([100, 10, 1])
RegressionModel(
  (fc): Linear(in_features=4, out_features=1, bias=False)
)


In [16]:
#this is what we call one epoch training
for i in range(1000):
  print("EPOCH", i)
  for i, (inputs, target) in enumerate(zip(sample_X, sample_y)):
    output = sample_model(inputs)
    loss = loss_fn(output,target)
    if i % 10 == 0:
      print("   step ",i)
      print(loss.item())
    # Backpropagation
    optim.zero_grad() # clear previous gradient
    loss.backward() # calculate gradient
    optim.step()

EPOCH 0
   step  0
4.836971267963008e-09
   step  10
2.1793824522831073e-09
   step  20
6.602027813329414e-09
   step  30
5.801104041580629e-09
   step  40
3.836936546264269e-09
   step  50
4.981330903319758e-09
   step  60
4.3692920392857104e-09
   step  70
6.1891798353030936e-09
   step  80
6.881180070195114e-09
   step  90
3.6392180380317996e-09
EPOCH 1
   step  0
4.836971267963008e-09
   step  10
2.1793824522831073e-09
   step  20
6.602027813329414e-09
   step  30
5.801104041580629e-09
   step  40
3.836936546264269e-09
   step  50
4.981330903319758e-09
   step  60
4.3692920392857104e-09
   step  70
6.1891798353030936e-09
   step  80
6.881180070195114e-09
   step  90
3.6392180380317996e-09
EPOCH 2
   step  0
4.836971267963008e-09
   step  10
2.1793824522831073e-09
   step  20
6.602027813329414e-09
   step  30
5.801104041580629e-09
   step  40
3.836936546264269e-09
   step  50
4.981330903319758e-09
   step  60
4.3692920392857104e-09
   step  70
6.1891798353030936e-09
   step  80
6.88

In [21]:
#lets see the total loss
loss_total = []
for inputs, target in zip(sample_X, sample_y):
  output = sample_model(inputs)
  loss = loss_fn(output,target)
  loss_total.append(loss.item())

loss_average = np.mean(loss_total)  # cuma menghitung nilai rata-rata dari lossnya

In [19]:
print(loss_average)

5.199135856837067e-09


In [22]:
#lets we see the parameters, that's the weight that we trained
for param in sample_model.parameters():
  print(param.data)

tensor([[1.0001, 2.0001, 2.9999, 3.9998]])


## 5. create inference function

In [ ]:
def inference(x1,x2,x3,x4):
  inputs = torch.tensor([[x1,x2,x3,x4]], dtype=torch.float32)
  inputs = inputs/2000
  output = sample_model(inputs)
  output*=2000  # Outputnya dikali 2000 lagi agar sesuai dengan fungsi yang kita buat sebelumnya

  return output[0].detach().numpy()

def function(x1, x2, x3, x4):

w1,w2,w3,w4=1,2,3,4

return x1*w1+x2*w2+x3*w3+x4*w4

In [ ]:
# Masukkan nilai x1, x2, x3, x4 yang ingin diprediksi
x1,x2,x3,x4 = 3,4,5,6 

# inference itu nilai predict dan function itu ambil data dari fungsi asli di awal
inference(x1,x2,x3,x4), function(x1,x2,x3,x4) # compare prediksi vs fungsi asli data

(array([49.999397], dtype=float32), 50)