### NumPy Array

In [3]:
#Membuat array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Array Dimention

In [6]:
# Membuat array 0 dimensi (0D)
import numpy as np

arr = np.array(42)
print(arr)

42


In [7]:
#Membuat array 1 dimensi (1D)
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [9]:
#Membuat array 2 dimensi (2D)
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
#Membuat array 3 dimensi (3D)
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array Indexing

In [25]:
#Mengakses array
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr1[2])
print(arr2[0, 2])
print(arr3[1, 0, 2])

3
3
9


### Negative Indexing

In [26]:
#Mengakses array dengan indeks negative (dari belakang)
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr1[-2])
print(arr2[0, -2])
print(arr3[1, 0, -2])

4
2
8


### Index Slicing

In [28]:
#Mengakses indeks sekaligus berdasarkan rentang yang ditentukan
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1[1:3])     #ingat 1:3 berarti dimulai dari 1 dan batasnya 3 berarti yang didapat indeks ke 1 dan 2

[2 3]


### Array DataType

In [29]:
#Cek tipe data pada NumPy array
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [30]:
#Kita juga bisa definisikan tipe data pada NumPy array
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1
