# Array

In [1]:
import numpy as np

### Membuat NumPy Array

In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Perbedaan Python List dengan NumPy Array

In [7]:
# Python List
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]
print(type(a)), print(type(b))

<class 'list'>
<class 'list'>


(None, None)

In [9]:
a + b    #Ketika ditambah maka jadi concat(gabung) padahal kita ingin itu dijumlahkan

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
a * b    #Ketika dikali tidak bisa katanya can't multiply

TypeError: can't multiply sequence by non-int of type 'list'

In [12]:
arrayA = np.array(a)
arrayB = np.array(b)
print(type(arrayA))
print(type(arrayB))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
arrayA + arrayB    #Nah kalau kita pakai np.array maka baru dia dijumlahkan

array([ 7,  9, 11, 13, 15])

In [14]:
arrayA * arrayB    #Di perkalian dan operasi matematika lain juga sama

array([ 6, 14, 24, 36, 50])

In [15]:
arrayA * 10    #Ini namanya konsep broadcasting jadi semua elemen di dalam array akan dikali dengan skalar

array([10, 20, 30, 40, 50])

In [16]:
#Contoh penerapan konsep np.array
y_pred = np.array([1, 0, 0, 1, 1, 0, 1, 1])
labels = np.array([0, 1, 0, 1, 1, 0, 1, 1])

mse = (1/len(labels)) * np.sum(np.square(y_pred - labels))
print(mse)

0.25


### Membuat array nol dimensi (0D)

In [17]:
import numpy as np

arr = np.array(42)
print(arr)

42


### Membuat array satu dimensi (1D)

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### Membuat array dua dimensi (2D)

In [1]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### Membuat array tiga dimensi (3D)

In [2]:
import numpy as np

arr = np.array([[[1, 2, 3],
                 [4, 5, 6]],
                [[7, 8, 9],
                 [10, 11, 12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Membuat NumPy array 0s dan 1s

In [3]:
import numpy as np

arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [6]:
arr = np.zeros((5, 2))
print(arr)

#array yang terbentuk yaitu array 0 berjumlah 5 yang masing2 diisi 2 elemen

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
import numpy as np

arr = np.ones((5, 7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [11]:
#Bisa juga buat untuk 3D

arr = np.ones(((3, 4, 2)))
print(arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


### Menghapus Array

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
#Menghpaus array tertentu

arrDelete = np.array(arr)
arrDelete = np.delete(arrDelete, 1, axis=0)    #Menghapus indeks ke 1
print(arrDelete)

#axis=0 itu karena kita menggunakan array 1 dimensi, kalau menggunakan lebih dari 1 dimensi
#dan ingin menghapus di dimensi lain makan gunakan 1 atau 2 tergantung di dimensi mana yang ingin dihapus

[[1 2 3]
 [7 8 9]]


In [16]:
#Menghapus seluruh isi array

del arrDelete

In [17]:
print(arrDelete)   #Karena sudah dihapus jadi tidak bisa diakses lagi

NameError: name 'arrDelete' is not defined

### Mengakses Array pada NumPy

In [18]:
# Ada di bagian teori

### Mengecek Tipe Data Pada NumPy Array

In [19]:
#Cek tipe data pada NumPy array
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [32]:
#Kita juga bisa definisikan tipe data pada NumPy array
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')
arr_int16 = np.array([1, 2, 3, 4], dtype=np.int16)
arr_int32 = np.array([1, 2, 3, 4], dtype=np.int32)
arr_uint = np.array([1, 2, 3, 4], dtype='I')
print(arr)
print(arr.dtype)
print(arr_int16)
print(arr_int16.dtype)
print(arr_int32)
print(arr_int32.dtype)
print(arr_uint)
print(arr_uint.dtype)

[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int16
[1 2 3 4]
int32
[1 2 3 4]
uint32


### Mengubah Tipe Data Pada NumPy Array

In [35]:
arr = np.array([1.1, 2.4, 3.7, 4.5])
arr, arr.dtype    #Tipe awalnya float64

(array([1.1, 2.4, 3.7, 4.5]), dtype('float64'))

In [37]:
arr = arr.astype('I')    #Kita ubah jadi uint32
arr, arr.dtype

(array([1, 2, 3, 4], dtype=uint32), dtype('uint32'))

### Fungsi Arange

In [49]:
arr = np.arange(10)
arr, print(type(arr))

<class 'numpy.ndarray'>


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), None)

In [52]:
#Kalau di List Python :
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [50]:
#Bisa juga menggunakan pengulangan for

for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [53]:
#Bisa juga menggunakan kelipatanabs
arr = np.arange(10, 20, 2)   #10 sampai 20 dengan kelipatan 2
print(arr)

[10 12 14 16 18]
