# Filter

In [1]:
import numpy as np

### Array Filtering
    Proses filter digunakan untuk mendapatkan beberapa bagian Array dari satu Array yang utuh. Filtering bekerja berdasarkan nilai boolean True atau False yang diterimanya.

In [ ]:
arr = np.array([41, 42, 43, 44, 45])
x = [True, False, True, False, True]

arr = arr[x]

print(arr)

# Dia mengembalikan nilai dari elemen yang sesuai dengan True pada array boolean x

[41 43 45]


### Filter pada NumPy Array 1D

In [5]:
arr = np.array([41, 42, 43, 44, 45])
filter_arr = arr > 42
arr = arr[filter_arr]

print(arr)
# Dia mengembalikan nilai dari elemen yang lebih besar dari 42 pada array boolean filter_arr karena yang lebih besar dari 42 dianggap True


arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
filter_arr2 = arr2 % 2 == 0
arr2 = arr2[filter_arr2]

print(arr2)
# Dia mengembalikan nilai dari elemen yang genap pada array boolean filter_arr2 karena yang genap dianggap True

[43 44 45]
[ 2  4  6  8 10]
