# Praktek Filtering

In [1]:
import numpy as np

### Filter pada Array 1D

In [ ]:
arr = np.array([41, 42, 43, 44, 45])
x = [True, False, True, False, True]
arr = arr[x]    # arr dimasukkan ke dalam x maka dia akan mengambil nilai True saja


print(arr)    

[41 43 45]


In [11]:
arr = np.array([41, 42, 43, 44, 45])
filter_array = arr > 42

filter_array    # Sebenarnya hasilnya gini, jadi dia akan sesuai dengan requirement kita, karena > 42 maka hasilnya seperti pada output berdasarkan nilai arr yang kita input
#Output: array([False, False,  True,  True,  True])


# Nah ketika kita lempar jadi indeks ke dalam array, maka dia akan mengambil nilai True saja
arr = arr[filter_array]
print(arr)    # Hasilnya adalah 43, 44, 45

[43 44 45]


### Filter pada NumPy Array 1D menggunakan lebih dari 1 kondisi

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

filter_array = (arr % 2 == 0) & (arr > 5)  # Menggunakan operator bitwise AND untuk menggabungkan dua kondisi
arr = arr[filter_array]  # Menggunakan filter_array untuk memfilter elemen-elemen yang memenuhi kedua kondisi

print(arr)

[ 6  8 10]


### Filter pada NumPy Array 2D menggunakan lebih dari 1 kondisi

In [13]:
arr = np.array([[1, 'One'],
                [2, 'Two'],
                [3, 'Three'],
                [4, 'Four'],
                [5, 'Five']])
arr.shape

(5, 2)

In [17]:
filter_array = np.array(['Two', 'Four'])
arr = arr[np.isin(arr[:, 1], filter_array)]  # Memfilter berdasarkan kolom kedua
print(arr)

[['2' 'Two']
 ['4' 'Four']]
