# Operation

### Array Iterating
    Proses iterasi atau loop bisa kita lakukan pada Python List juga bisa kita lakukan pada NumPy Array. Loop dilakukan terhadap setiap elemen yang ada paa suatu Array. Jika kita hanya menggunakan iterating biasa ini melakukan looping pada level indeks.

In [ ]:
# Iterasi pada NumPy Array 1D

import numpy as np
arr = np.array([1, 2, 3, 4, 5])

for x in arr:
    print(x)

1
2
3
4
5


In [2]:
# Iterasi pada NumPy Array 2D
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr2d:
    print(x)

[1 2 3]
[4 5 6]


In [3]:
# Iterasi pada NumPy Array 3D
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in arr3d:
    print(x)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


### Array Iteratting nditer()
    Fungsi nditer() adalah fungsi khusus untuk membantu melakukan iterasi pada setiap elemen di level skalar. Ini akan membantu kita mengakses elemen yang berada pada Array dengan dimensi besar

In [4]:
# Iterasi dengan np.nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


### Array Iterating ndenumerate(
    Fungsi ndenumerate() adalah fungsi khusus untuk membantu melakukan iterasi pada setiap elemen di level skalar sekaligus bersama indeksnya.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

for idx, x in np.ndenumerate(arr):
    print(idx, x)
    

# jadi dia akan mengembalikan index dan value dari array

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


### Array Join
    Join merupakan proses untuk menggabungkan 2 atau lebih array dengan 1 array menggunakan fungsi concatenate() dan stack(). Proses joining berdasarkan axis yang bermula nilai 0 berarti secara flatten.

#### Menggunakan Fungsi concatenante()

In [7]:
# Join terhadap 2 array 1D
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

# Karena axisnya tidak kita definisikan, maka defaultnya adalah 0

[1 2 3 4 5 6]


In [8]:
# Join terhadap 2 array 2D
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


#### Menggunakan fungsi stack()

In [9]:
# Join terhadap 2 array 1D
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
# Di stack() ada juga fungsi lain yaitu hstack() dan vstack()
# hstack() untuk horizontal stack
arrH = np.hstack((arr1, arr2))
arrV = np.vstack((arr1, arr2))
print(arrH)
print(arrV)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### Array Split
    Split berfungsi untuk membagi 1 Array menjadi 2 atau lebih Array menggunakan fungsi array_split().

In [12]:
# Split array 1D
arr = np.array([1, 2, 3, 4, 5, 6])
arr = np.split(arr, 3)
print(arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# Split array 2D axis=0
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
arr = np.array_split(arr, 4, axis=0)
print(arr)

# Kalau axis=0 pembagiannya flatten(rata)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [24]:
# Split array 2D axis=1

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
arr = np.array_split(arr, 4, axis=1)
print(arr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64), array([], shape=(6, 0), dtype=int64)]


### Array Search
    Kita bisa melakukan proses pencarian terhadap nilai tertentu pada Array dengan menggunakan fungsi where(). Hasil dari proses pencarian berupa indeks dari posisi nilai tersebut.

In [31]:
# Search array 1D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x = np.where(arr == 4)
y = np.where(arr*2 == 6)
print(x)    # Maka akan mengembalikan index dari 4
print(y)    # Maka akan mengembalikan index dari perkalian 2 yang hasilnya 6

(array([3]),)
(array([2]),)


### Array Sort
    Sort berarti kit menyusun elemen-elemen yang ada pada Array secara teratur. Penyusunan dapat dilakukan secara ascending(ASC) ataupun descending(DESC) menggunakan fungsi sort().

In [34]:
# Sort array 1D
arr = np.array([3, 2, 1, 4, 5])
print(np.sort(arr))    # Mengembalikan array baru yang sudah di sort


# Jika indeks berupa string jug bisa di sort
arr = np.array(['banana', 'apple', 'orange'])
print(np.sort(arr))    # Mengembalikan array baru yang sudah di sort berdasarkan abjad

[1 2 3 4 5]
['apple' 'banana' 'orange']
