# Praktek Array

In [1]:
import numpy as np

### Iterasi pada Array 1D

In [3]:
arr = np.array([1, 2, 3, 4, 5])

for i in arr:
    print(i)

1
2
3
4
5


### Iterasi pada Array 2D

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
    print(i)

[1 2 3]
[4 5 6]


### Iterasi pada Array 3D atau lebih

In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


### Iterasi dengan nditer()

In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in np.nditer(arr):
    print(i)
    
# Dengan menggunakan nditer() kita bisa akses skalar array multi dimensi

1
2
3
4
5
6
7
8
9
10
11
12


### Iterasi dengan ndenumerate() 1D

In [13]:
arr = np.array([1, 2, 3, 4, 5])

for idx, i in np.ndenumerate(arr):
    print(idx, i)
    
# Dengan menggunakan ndenumerate() kita bisa akses indeks dan skalar array multi dimensi

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


### Iterasi dengan ndenumerate() 2D

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for idx, i in np.ndenumerate(arr):
    print(idx, i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


### Join terhadap 2 Array 1D

In [18]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

arr = np.concatenate((arr1, arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


### Join terhadap 2 Array 2D

In [21]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)
print(arr.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


### Stack terhadap 2 Array 1D
Stack ini akan membuat dimensi baru. kita bisa stack dengan 2 cara yaitu hstack() dan vstack(). By default dia akan menggunakan vstack()

In [24]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# nah itu kan masing-masing 1D

arr = np.stack((arr1, arr2))
#kita stack dia akan berubah jadi 2D, dia konsepnya mirip kayak concatenate tapi dia nambahin dimensi baru

print(arr)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


### Split terhadap 1 Array 1D


In [28]:
arr = np.array([1, 2, 3, 4, 5])

arr = np.array_split(arr, 2)
print(arr)

# pembagian pada array_split() itu tidak harus sama, dia akan membagi sesuai dengan panjang array yang kita punya

[array([1, 2, 3]), array([4, 5])]


### Split terhadap 1 Array 2D

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr = np.array_split(arr, 2, axis=0) # bisa juga axis=1
print(arr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


### Search pada Array 1D

In [37]:
arr = np.array([1, 2, 3, 4, 5])

x = np.where(arr == 3)
y = np.where(arr*2 == 4)    # arrnya bisa kita operasikan dulu baru kita cari
print(x)
print(y)

(array([2]),)
(array([1]),)


### Sort pada Array 1D

In [42]:
arr = np.array([3, 2, 1, 4, 5, 0])
arr2 = np.array(['pisang', 'apel', 'jeruk', 'mangga', 'kiwi', 'anggur'])

x = np.sort(arr)
y = np.sort(arr2)
print(x)
print(y)

[0 1 2 3 4 5]
['anggur' 'apel' 'jeruk' 'kiwi' 'mangga' 'pisang']


### Sort pada Array 2D

In [44]:
arr = np.array([[3, 2, 1], [4, 5, 0]])
arr2 = np.array([['pisang', 'apel', 'jeruk'], ['mangga', 'kiwi', 'anggur']])

x = np.sort(arr) # axis=0 itu kolom, axis=1 itu baris
y = np.sort(arr2) # axis=0 itu kolom, axis=1 itu baris
print(x)
print(y)

[[1 2 3]
 [0 4 5]]
[['apel' 'jeruk' 'pisang']
 ['anggur' 'kiwi' 'mangga']]
